CMAKE_MINIMUM_REQUIRED(VERSION 3.9)
CMAKE_POLICY(SET CMP0079 NEW)

PROJECT(B3)

SET(CMAKE_EXPORT_COMPILE_COMMANDS ON)

SET(CMAKE_CXX_STANDARD 20)
SET(CMAKE_CXX_STANDARD_REQUIRED ON)

SET(CMAKE_C_STANDARD 17)
SET(CMAKE_C_STANDARD_REQUIRED ON)

IF(NOT CMAKE_BUILD_TYPE)

    OPTION(B33_RUN_TESTS "Run tests before starting the main loop" ON)
    SET(CMAKE_BUILD_TYPE "Debug")

ENDIF()

IF(CMAKE_BUILD_TYPE STREQUAL "TestsOnly")

    OPTION(B33_ONLY_TESTS "Run tests before starting the main loop" ON)
    OPTION(B33_DEBUG_BUILD "Enables debug build" ON)

ENDIF()

IF(CMAKE_BUILD_TYPE STREQUAL "Debug")

    OPTION(B33_DEBUG_BUILD "Enables debug build" ON)

ENDIF()


SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/Bin/${CMAKE_SYSTEM_PROCESSOR}/${CMAKE_BUILD_TYPE})
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/Lib/${CMAKE_SYSTEM_PROCESSOR}/${CMAKE_BUILD_TYPE})
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/Lib/${CMAKE_SYSTEM_PROCESSOR}/${CMAKE_BUILD_TYPE})

ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/Engine)
ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/Projects)

