CMAKE_MINIMUM_REQUIRED(VERSION 3.9)
PROJECT(B3_Engine)

IF (NOT (${CMAKE_CXX_STANDARD} STREQUAL "20"))

    MESSAGE("CMAKE_CXX_STANDARD isn't C++20. This engine was build with C++20 in mind.")

ENDIF()

OPTION(B33_RUN_TESTS "Run tests before starting the main loop")
OPTION(B33_DEBUG_BUILD "Enables debug build")


IF(NOT TARGET_ARCH OR TARGET_ARCH STREQUAL "")

    SET(TARGET_ARCH "unknown")

ENDIF()

IF(B33_DEBUG_BUILD STREQUAL "ON")

    LIST(APPEND B33_COMPILE_DEFINITIONS _DEBUG)

ENDIF()

IF(B33_RUN_TESTS STREQUAL "ON")

    LIST(APPEND B33_COMPILE_DEFINITIONS _B33_TESTS)

ENDIF()

IF(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")

    LIST(APPEND B33_COMPILE_DEFINITIONS _MSVC)

ENDIF()

IF(CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")

    LIST(APPEND B33_COMPILE_DEFINITIONS _Clang)

ENDIF()

IF(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")

    LIST(APPEND B33_COMPILE_DEFINITIONS _GNU)

ENDIF()

LIST(APPEND B33_COMPILE_DEFINITIONS UNICODE)
LIST(APPEND B33_COMPILE_DEFINITIONS _UNICODE)
LIST(APPEND B33_COMPILE_DEFINITIONS _CRT_SECURE_NO_WARNINGS)

ADD_COMPILE_DEFINITIONS(${B33_COMPILE_DEFINITIONS})
SET(B33_COMPILE_DEFINITIONS "${B33_COMPILE_DEFINITIONS}" PARENT_SCOPE)

ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/Core)
ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/System)
ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/Math)
ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/Application)
ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/Rendering)
ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/External)
