CMAKE_MINIMUM_REQUIRED(VERSION 3.15)

IF (NOT (${CMAKE_CXX_STANDARD} STREQUAL "20"))

    MESSAGE("CMAKE_CXX_STANDARD isn't C++20. This engine was build with C++20 in mind.")

ENDIF()

ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/Core)
ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/System)
ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/Math)
ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/Application)
ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/Rendering)
ADD_SUBDIRECTORY(${CMAKE_CURRENT_SOURCE_DIR}/External)
